# configMap for setup env 

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: frontend
#   namespace: roboshop
#   labels:
#     component: frontend
#     project: roboshop
#     tier: web
# data:
#   CART_ENDPOINT: "cart:8080"
#   DB_HOST: "mysql"

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # deployment labels 
  labels:
    component: frontend
    project: roboshop
    tier: web

spec: 
  replicas: 1 
  # these are the labels replica set use to create pod replicas, this should match pod lables
  selector:
    matchLabels:
      component: frontend
      project: roboshop
      tier: web
  # this is pod definition
  template:
    metadata:
      labels:
        component: frontend
        project: roboshop
        tier: web
    spec:
      containers:
      - name: frontend
        image: vinod9072/frontend:v1 
        # envFrom:
        # - configMapRef:
        #     name: frontend
---
# service

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop 
  labels:
    component: frontend
    project: roboshop
    tier: web
spec:
  type: LoadBalancer 
  selector:
    component: frontend
    project: roboshop
    tier: web
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

