apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop

  # deployment labels 
  labels:
    component: mongodb
    project: roboshop
    tier: database

spec: 
  replicas: 1
  # these are the labels replica set use to create pod replicas, this should match pod lables
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      tier: database
  # this is pod definition
  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        tier: database
    spec:
      containers:
      - name: mongodb
        image: vinod9072/mongodb:v1 

